CREATE TYPE IF NOT EXISTS role AS ENUM ('user', 'admin');

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" varchar(64) NOT NULL UNIQUE,
  name text,
  email varchar(320),
  "passwordHash" varchar(255),
  "loginMethod" varchar(64),
  role role NOT NULL DEFAULT 'user',
  "createdAt" timestamp NOT NULL DEFAULT now(),
  "updatedAt" timestamp NOT NULL DEFAULT now(),
  "lastSignedIn" timestamp NOT NULL DEFAULT now()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS "passwordHash" varchar(255);

CREATE TABLE IF NOT EXISTS user_locations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL UNIQUE,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  accuracy double precision,
  "updatedAt" timestamp NOT NULL DEFAULT now()
);
